const BabiliPlugin = require('babili-webpack-plugin');
const CopyPlugin = require('copy-webpack-plugin');
const path = require('path');
const { EnvironmentPlugin } = require('webpack');
const HtmlPlugin = require('html-webpack-plugin');

const HTML_MINIFIER_OPTIONS = {
  collapseBooleanAttributes: true,
  collapseInlineTagWhitespace: true,
  collapseWhitespace: true,
  includeAutoGeneratedTags: false,
  removeAttributeQuotes: true,
  removeComments: true,
  removeOptionalTags: true,
  removeScriptTypeAttributes: true,
  removeStyleLinkTypeAttributes: true,
  sortAttributes: true,
  sortClassName: true,
};

module.exports = (env = process.env.NODE_ENV) => {
  process.env.NODE_ENV = env;
  return {
    devServer: {
      historyApiFallback: true,
    },
    devtool: 'source-map',
    entry: {
      main: path.resolve(__dirname, 'src', 'main.js'),
    },
    module: {
      rules: [
        {
          test: /\.js$/,
          loader: 'babel-loader',
        },
      ],
    },
    output: {
      chunkFilename: env === 'production' ? '[name].[chunkhash].js' : '[name].js?[chunkhash]',
      filename: env === 'production' ? '[name].[chunkhash].js' : '[name].js?[chunkhash]',
      path: path.resolve(__dirname, 'public'),
      publicPath: '/',
    },
    plugins: [
      new EnvironmentPlugin({
        NODE_ENV: env || 'development',
      }),
      new HtmlPlugin({
        minify: env === 'production' ? HTML_MINIFIER_OPTIONS : false,
        template: path.resolve(__dirname, 'src', 'templates', 'index.html.ejs'),
        title: 'MastodonKaigi',
      }),
      ...(env === 'production' ? [
        new CopyPlugin([
          {
            from: path.resolve(__dirname, 'src', 'templates', '_redirects'),
          },
          {
            from: path.resolve(__dirname, 'src', 'templates', '_headers'),
          },
        ]),
        new BabiliPlugin(),
      ] : []),
    ],
  };
};
